### ISSUE TITLE
Error at #generate_unique_sid when saving the session to redis

### ISSUE THREAD

**Issue by itsmechlark** [redis-store/redis-rack#30]
If you check [rack/session/redis.rb#L39](https://github.com/redis-store/redis-rack/blame/master/lib/rack/session/redis.rb#L39) provide 3 arguments to Redis#setnx which it only accept 2 arguments(key & value). Why is it your including the `@default_options` when saving the session to `redis`?

**Browser HAR File:** [debug.har.zip](https://github.com/redis-store/redis-rack/files/1328121/debug.har.zip)
**Log:**
```
api_1       | 02:36:06 app.1   | ArgumentError - wrong number of arguments (given 3, expected 2):
api_1       | 02:36:06 app.1   |   redis (3.3.3) lib/redis.rb:790:in `setnx'
api_1       | 02:36:06 app.1   |   redis-namespace (1.5.3) lib/redis/namespace.rb:435:in `call_with_namespace'
api_1       | 02:36:06 app.1   |   redis-namespace (1.5.3) lib/redis/namespace.rb:321:in `method_missing'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:39:in `block (2 levels) in generate_unique_sid'
api_1       | 02:36:06 app.1   |   connection_pool (2.2.1) lib/connection_pool.rb:64:in `block (2 levels) in with'
api_1       | 02:36:06 app.1   |   connection_pool (2.2.1) lib/connection_pool.rb:63:in `handle_interrupt'
api_1       | 02:36:06 app.1   |   connection_pool (2.2.1) lib/connection_pool.rb:63:in `block in with'
api_1       | 02:36:06 app.1   |   connection_pool (2.2.1) lib/connection_pool.rb:60:in `handle_interrupt'
api_1       | 02:36:06 app.1   |   connection_pool (2.2.1) lib/connection_pool.rb:60:in `with'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:88:in `with'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:38:in `block in generate_unique_sid'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:36:in `loop'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:36:in `generate_unique_sid'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:52:in `block in get_session'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:75:in `with_lock'
api_1       | 02:36:06 app.1   |   redis-rack (2.0.2) lib/rack/session/redis.rb:49:in `get_session'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/session/abstract/id.rb:425:in `find_session'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/session/abstract/id.rb:280:in `load_session'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/session/abstract_store.rb:56:in `block in load_session'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/session/abstract_store.rb:64:in `stale_session_check!'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/session/abstract_store.rb:56:in `load_session'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/request/session.rb:216:in `load!'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/request/session.rb:208:in `load_for_read!'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/request/session.rb:90:in `[]'
api_1       | 02:36:06 app.1   |   warden (1.2.7) lib/warden/session_serializer.rb:31:in `fetch'
api_1       | 02:36:06 app.1   |   warden (1.2.7) lib/warden/proxy.rb:213:in `user'
api_1       | 02:36:06 app.1   |   warden (1.2.7) lib/warden/proxy.rb:145:in `authenticated?'
api_1       | 02:36:06 app.1   |   config/initializers/rack.rb:92:in `block in <main>'
api_1       | 02:36:06 app.1   |   lib/rack/rate_limit.rb:13:in `max_per_hour'
api_1       | 02:36:06 app.1   |   rack-throttle (0.5.0) lib/rack/throttle/time_window.rb:13:in `allowed?'
api_1       | 02:36:06 app.1   |   lib/rack/rate_limit.rb:7:in `call'
api_1       | 02:36:06 app.1   |   warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
api_1       | 02:36:06 app.1   |   warden (1.2.7) lib/warden/manager.rb:35:in `catch'
api_1       | 02:36:06 app.1   |   warden (1.2.7) lib/warden/manager.rb:35:in `call'
api_1       | 02:36:06 app.1   |   versionist (1.6.0) lib/versionist/middleware.rb:39:in `_call'
api_1       | 02:36:06 app.1   |   versionist (1.6.0) lib/versionist/middleware.rb:17:in `call'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/etag.rb:25:in `call'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/head.rb:12:in `call'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
api_1       | 02:36:06 app.1   |   activerecord (5.0.6) lib/active_record/migration.rb:553:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
api_1       | 02:36:06 app.1   |   activesupport (5.0.6) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
api_1       | 02:36:06 app.1   |   activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
api_1       | 02:36:06 app.1   |   activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
api_1       | 02:36:06 app.1   |   better_errors (2.3.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
api_1       | 02:36:06 app.1   |   better_errors (2.3.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
api_1       | 02:36:06 app.1   |   better_errors (2.3.0) lib/better_errors/middleware.rb:57:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
api_1       | 02:36:06 app.1   |   railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'
api_1       | 02:36:06 app.1   |   railties (5.0.6) lib/rails/rack/logger.rb:24:in `block in call'
api_1       | 02:36:06 app.1   |   activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
api_1       | 02:36:06 app.1   |   activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in `tagged'
api_1       | 02:36:06 app.1   |   activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `tagged'
api_1       | 02:36:06 app.1   |   railties (5.0.6) lib/rails/rack/logger.rb:24:in `call'
api_1       | 02:36:06 app.1   |   sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
api_1       | 02:36:06 app.1   |   request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/method_override.rb:22:in `call'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/runtime.rb:22:in `call'
api_1       | 02:36:06 app.1   |   activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
api_1       | 02:36:06 app.1   |   actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'
api_1       | 02:36:06 app.1   |   rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
api_1       | 02:36:06 app.1   |   rack-mini-profiler (0.10.5) lib/mini_profiler/profiler.rb:282:in `call'
api_1       | 02:36:06 app.1   |   rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'
api_1       | 02:36:06 app.1   |   railties (5.0.6) lib/rails/engine.rb:522:in `call'
api_1       | 02:36:06 app.1   |   puma (3.10.0) lib/puma/configuration.rb:225:in `call'
api_1       | 02:36:06 app.1   |   puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
api_1       | 02:36:06 app.1   |   puma (3.10.0) lib/puma/server.rb:437:in `process_client'
api_1       | 02:36:06 app.1   |   puma (3.10.0) lib/puma/server.rb:301:in `block in run'
api_1       | 02:36:06 app.1   |   puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
api_1       | 02:36:06 app.1   |   logging (2.2.2) lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by itsmechlark** [comment]
Added this code for temporary fixed, hopefully, it will not cause any issue:
```
def generate_unique_sid(session)
    loop do
      sid = generate_sid
      first = with do |c|
        [*c.setnx(sid, session)].first
      end
      break sid if [1, true].include?(first)
    end
  end
```

**Comment by tubbo** [comment]
@itsmechlark why not submit as a pull request if you have a fix?

**Comment by tubbo** [comment]
actually, wait a second @itsmechlark...I didn't notice the location of the backtrace. It looks like you're calling `Redis#setnx` when it really should be calling `Redis::Store#setnx`. Since `Redis::Store` is a subclass of `Redis`, it overrides `#setnx` to include the 3rd argument.

Here's what I'm talking about: https://github.com/redis-store/redis-store/blob/master/lib/redis/store/ttl.rb#L12-L18

Now I'm wondering if the `ConnectionPool` logic somehow gives you back a `Redis` instance instead of a `Redis::Store`...

**Comment by tubbo** [comment]
@itsmechlark does this still happen for you?

**Comment by itsmechlark** [comment]
@tubbo, it's fixed.  I forgot to use `Redis::Store` instance in `ConnectionPool`. Thank you.
