### ISSUE TITLE
Rack3 support

### ISSUE THREAD

**Issue by n-rodriguez** [redis-store/redis-rack#71]
Hi there! Any plans to support it?
Thank you!

**Comment by tubbo** [comment]
Hey @n-rodriguez, just did a quick cursory glance and this shouldn't be too hard to support.

**Comment by tubbo** [comment]
@n-rodriguez can you try the master branch of this gem and see if that works on rack 3 now?

**Comment by n-rodriguez** [comment]
> @n-rodriguez can you try the master branch of this gem and see if that works on rack 3 now?

Thank you for the quick answer! 
My app have some gems that depends on `rack '>= x.x.x', '< 3'` so I need to update them too to switch to Rack 3. I'll give you some feedback when it's done.

**Comment by soumyaray** [comment]
Hi @tubbo I tried installing v2.1.4 from Github as I don't see this fix for Rack3 on RubyGems yet. Its installing fine and I can see v2.1.4 in the `GIT` section of my `Gemfile.lock`. 

I'm setting up redis-rack for the session using:
```
      use Rack::Session::Redis,
          expire_after: ONE_MONTH,
          redis_server: ENV.delete('REDIS_URL')
```

I can confirm that REDIS_URL is found prior to this line.

However, once I try to find a session variable (e.g., `session[:account]`), I get this error:
```
Puma caught this error: unknown keyword: :scheme (ArgumentError)
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-client-0.14.1/lib/redis_client/config.rb:21:in `initialize'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-client-0.14.1/lib/redis_client/config.rb:184:in `initialize'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-client-0.14.1/lib/redis_client.rb:143:in `new'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-client-0.14.1/lib/redis_client.rb:143:in `config'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-5.0.6/lib/redis/client.rb:23:in `config'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-5.0.6/lib/redis.rb:157:in `initialize_client'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-5.0.6/lib/redis.rb:73:in `initialize'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-store-1.9.2/lib/redis/store.rb:17:in `initialize'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-store-1.9.2/lib/redis/store/factory.rb:26:in `new'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-store-1.9.2/lib/redis/store/factory.rb:26:in `create'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/redis-store-1.9.2/lib/redis/store/factory.rb:9:in `create'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/redis-rack-15e12b33d222/lib/redis/rack/connection.rb:39:in `store'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/redis-rack-15e12b33d222/lib/redis/rack/connection.rb:24:in `with'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/redis-rack-15e12b33d222/lib/rack/session/redis.rb:82:in `with'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/redis-rack-15e12b33d222/lib/rack/session/redis.rb:88:in `get_session_with_fallback'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/redis-rack-15e12b33d222/lib/rack/session/redis.rb:38:in `block in find_session'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/redis-rack-15e12b33d222/lib/rack/session/redis.rb:70:in `with_lock'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/redis-rack-15e12b33d222/lib/rack/session/redis.rb:37:in `find_session'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:320:in `load_session'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:195:in `load!'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:187:in `load_for_read!'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:89:in `[]'
/Users/soumyaray/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:470:in `[]'
```
I didn't seem to have this issue with prior versions.
Is there any special setup procedure we should be using for this Rack3 fix?

**Comment by n-rodriguez** [comment]
@soumyaray see https://github.com/redis-store/redis-store/pull/359

**Comment by soumyaray** [comment]
Thanks @n-rodriguez that was the issue -- commenting there. 

@tubbo sorry and please disregard the above.
